/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include "gpio.h"

int main(void)
{
    uint8_t currentState = 0;
    uint8_t previousState = 0;
    uint8_t pressCount = 0;

    GPIO_Init();
    LED_AllOff();

    while (1)
    {
        currentState = GPIO_ReadSwitch();

        /* Rising edge detection */
        if ((currentState == 1) && (previousState == 0))
        {
            pressCount++;

            if (pressCount == 1)
                LED_GreenOn();
            else if (pressCount == 2)
                LED_BlueOn();
            else if (pressCount == 3)
            {
                LED_AllOff();
                pressCount = 0;  // Reset cycle
            }
        }

        previousState = currentState;
    }
}

