/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include "gpio.h"

int main(void)
{
    uint8_t currentState = 1;
    uint8_t previousState = 0;

    GPIO_Init();

    while (1)
    {
        currentState = GPIO_ReadSwitch();

        /* Detect rising edge: LOW → HIGH */
        if ((currentState == 1) && (previousState == 0))
        {
            GPIO_ToggleRedLED();
        }

        previousState = currentState;
    }
}
